# Generated by Django 2.1.1 on 2018-10-03 19:47

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('rootApp', '0002_auto_20180930_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspect',
            name='subject',
            field=models.IntegerField(choices=[(1, 'МАТЕМАТИКА'), (2, 'ФИЗИКА'), (3, 'ИСТОРИЯ'), (4, 'ХИМИЯ'), (5, 'БИОЛОГИЯ'), (6, 'ИНФОРМАТИКА'), (7, 'ЛИНГВИСТИКА'), (8, 'ЭКОНОМИКА')], default=1),
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='tags',
        ),
        migrations.AddField(
            model_name='conspect',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
