# Generated by Django 2.1.1 on 2018-10-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0004_auto_20181005_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conspect',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='raters',
        ),
    ]
